# Generated by Django 3.2.16 on 2022-10-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeeinformation',
            options={'verbose_name': 'Employee Information', 'verbose_name_plural': 'Employees Information'},
        ),
    ]
